### PR TITLE
Configure terminals automatically using the script file

### PR DESCRIPTION
**Pull request by BushraAsif**

### CODE REVIEW

**Review by shahbaz-mehar — COMMENTED** [review]
Changes have been reviewed.

**Comment by emicha** [comment]
@BushraAsif When and how is this script run?

**Comment by BushraAsif** [comment]
> @BushraAsif When and how is this script run?

This is a part of workflows and we will only use this in Github to run cypress tests.

**Comment by emicha** [comment]
> > @BushraAsif When and how is this script run?
> 
> This is a part of workflows and we will only use this in Github to run cypress tests.

Isn't altapay_config.php run at bootstrap of the application?

**Comment by BushraAsif** [comment]
> > > @BushraAsif When and how is this script run?
> > 
> > 
> > This is a part of workflows and we will only use this in Github to run cypress tests.
> 
> Isn't altapay_config.php run at bootstrap of the application?

Yes, we bootstrap Magento in the custom file(altapay_config.php). But in that file, we commented out the last line which means this will only get triggered when we uncomment it. And we will uncomment it using workflows. Without workflows, the bootstrap wouldn't run.

**Review by emicha — APPROVED** [review]

**Pull request merged**
